sudo: required
services:
  - docker

before_install:
  - docker build -t mihaelagog/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true mihaelagog/docker-react npm run test -- --coverage